### ISSUE TITLE
start_props and stop_props topics not working

### ISSUE THREAD

**Issue by 5yler** [ATLFlight/snav_ros#3]
I am running snav_ros v1.0.0 with snav 1.2.31. The /start_props and /stop_props ROS topics do not seem to have an effect on the vehicle's behavior. I tried publishing to /stop_props once the propellers were spinning and nothing changed. 

I am able to publish a desired velocity to /cmd_vel once the vehicle has been armed with an RC transmitter, which definitely affects the rate the propellers are spinning. Is there something else I should be doing in addition to publishing to /start_props or /stop props? Please advise.

**Comment by r1b4z01d** [comment]
I'm also not able to start the motors via the ros topic. I am running SNAV 1.2.53.1 with mv 1.14. Any insight would be great.

**Comment by mikeshomin** [comment]
You need to be publishing on /cmd_vel before publishing to /start_props.  This is a SNAV feature, and it needs to have a command before arming.  Also, to stop the props, you'll need to make sure that you're RC has channel 7 high to allow API commands if the RC is on.

**Comment by 5yler** [comment]
I tried publishing to /start_props after publishing to /cmd_vel and nothing happened, both with RC transmitter on and turned off. Any ideas? Does channel 7 need to be set to to high with RC transmitter on for /start_props to work in addition to /stop_props?

**Comment by shomin** [comment]
Are you continuously publishing to /cmd_vel?  SNAV expects to have continuous cmd input before starting the props.

**Comment by 5yler** [comment]
Yes, I am publishing to /cmd_vel at a rate of 85 Hz and /start_props still is not working for me. I tried manually arming the vehicle, after that publishing to /cmd_vel has an effect.
I am trying with this command:
```bash
rostopic pub /start_props std_msgs/Empty "{}"
```

However, I was able to get /stop_props to work while publishing to /cmd_vel at 85 Hz and then publishing through command line:
```bash
rostopic pub /stop_props std_msgs/Empty "{}"
```

**Comment by 5yler** [comment]
I modified the source code of `snav_interface.cpp`:
```c++
void SnavInterface::StartPropsCallback(const std_msgs::Empty::ConstPtr& msg)
{
  sn_update_data();
  int sn_spin_props_result = sn_spin_props();
  ROS_INFO("sn_spin_props_result: %d", sn_spin_props_result);
}
```
When I call the /start_props topic, I get the following result:
```
[ INFO] [1520001409.558925844]: sn_spin_props_result: 0
```
According to the SNAV Developer Guide the function returns 0 if attempt was received.

I tried running the `snav_test_receive_data` executable from `snav_api_examples` to check the mode and get the following output:
```
------------------ SNAPDRAGON NAVIGATOR DATA [46] ------------------
Mode: SN_SENSOR_ERROR_MODE
Prop state: SN_PROPS_STATE_NOT_SPINNING
flight control thinks vehicle is ON GROUND
```
When I manually arm it and then publish to /cmd_vel to control the propellers, the output is the following:
```
------------------ SNAPDRAGON NAVIGATOR DATA [579] ------------------
Mode: SN_THRUST_ANGLE_MODE
Prop state: SN_PROPS_STATE_SPINNING
flight control thinks vehicle is NOT ON GROUND
```

I tried changing `snav_ros.launch` to add the following parameter:
```xml
<param name="sn_rc_cmd_type" value="SN_RC_THRUST_ANGLE_CMD"/>
```
When I started snav_ros I got the following output:
```
[ INFO] [1400.299443237]: cmd_vel SNAV cmd type: SN_RC_THRUST_ANGLE_CMD
[ INFO] [1400.299652455]: cmd_vel SNAV mapping : RC_OPT_LINEAR_MAPPING
[ INFO] [1400.299980684]: DSP offset: 1000582243341 ns

Input 2 below minimum possible value. Using minimum possible [105.000000].
Input 2 below minimum possible value. Using minimum possible [105.000000].
Input 2 below minimum possible value. Using minimum possible [105.000000].
Input 2 below minimum possible value. Using minimum possible [105.000000].
Input 2 below minimum possible value. Using minimum possible [105.000000].
Input 2 below minimum possible value. Using minimum possible [105.000000].
Input 2 below minimum possible value. Using minimum possible [105.000000].
Input 2 below minimum possible value. Using minimum possible [105.000000].
Input 2 below minimum possible value. Using minimum possible [105.000000].
Input 2 below minimum possible value. Using minimum possible [105.000000].
```

When publishing to /cmd_vel and /start_props I was able to get the propellers to start spinning. However it seems there is something wrong about the command mapping. In previous tests when manually arming the vehicle in thrust/angle mode and then publishing to /cmd_vel, I was able to get stable flight by publishing values between -1 and 1 for the linear x, y, z fields of the Twist message and I never got the same error applying to command mapping. What are the expected with SN_RC_THRUST_ANGLE_CMD and RC_OPT_LINEAR_MAPPING? Please advise. Thanks!
