### ISSUE TITLE
Cannot locate rosdep definition for [snav_msgs]

### ISSUE THREAD

**Issue by SunggooJung** [ATLFlight/snav_ros#4]
I am trying to use this snav_ros package, however, when I try to install ros dependencies I got an error like below

have any ideas about this?
```
$ rosdep install . --from-paths
rosdep detected OS: [linaro] aliasing it to: [ubuntu]
ERROR: the following packages/stacks could not have their rosdep keys resolved
to system dependencies:
snav_ros: Cannot locate rosdep definition for [snav_msgs]
```

**Comment by torgeha** [comment]
I have the same issue, any pointers?

**Comment by Saradhara** [comment]
Hi, I am able to build the sanv ros on the docker container. The missing part was the sanv_msg git. snav ros uses snav msgs to communicate using publish and subscribe. So clone the snav_msg git and than do catkin_make. This worked for me.
